---
title: "STA160 Final Project Code"
author: "Duy Nguyen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(sf)
library(TTR)
#library(ggfortify)
library(forecast)
library(tseries)
library(astsa)
```

```{r}
dat = read_csv("Sacramento Average Anomaly.csv")
```

```{r}
test = ts(dat$Anomaly, start = dat$Year[1], frequency = 1)
```
EDA Stuff
```{r}
ggplot(dat, mapping = aes(x = Year, y = Temps)) + 
  geom_line() + 
  #geom_ribbon(aes(x = Year, y = MAA, ymin = MAA - Unc, ymax = MAA + Unc), alpha = 0.2) + 
  labs(title = "Sacramento Average Temperatures Yearly", x = "Years", y = "Average Temperatures") #+ 
  #geom_line(aes(y = MA), color = "red") #+ 
  #geom_smooth(color = "blue", fill = "red")

ggsave("Year.png", width = 10, height = 3)
```


```{r}
series = ts(dat$Anomaly, start = dat$Year[1]) # DISCARDED

autoplot(ma(series, 15))
```

```{r}
full_raw = read_csv("Sacramento Data Anomaly FULL.csv")
```

```{r}
full = ts(full_raw$Temps, start = c(full_raw$Year[1], full_raw$Month[1]), frequency = 12)
```

```{r}

autoplot(full) + 
  labs(title = "Sacramento Monthly Average Temperatures", y = "Monthly Temperature")
ggsave("Month.png", width = 10, height = 3)
```


```{r}
full %>% decompose() %>% autoplot() + 
  labs(title = "Decomposed Sacramento Time Series Temperature") + 
  scale_x_continuous(breaks = scales::extended_breaks(10))
```




```{r}
wrong = ts(full_raw$Anomaly, start = c(full_raw$Year[1], full_raw$Month[1]), frequency = 12)
seasonplot(wrong, main = "Seasonal Plot of Anomaly", ylab = "Anomaly")
```

```{r}

seasonplot(full, col = rainbow(150), year.labels = F, 
           main = "Seasonal Plot of Sacramento Temperatures")

```



# Summary
```{r}
library(flextable)
short_table = data.frame(matrix(ncol = 12, nrow = 5))
months = c("Jan", "Feb", "Mar", "Apr", "May", "Jun",
           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
#row_name = c("Min", "1st_Q", "Mean", "3rd_Q", "Max")
#short_table[, 1] = row_name
for (i in 1:12)
{
  temp = full_raw$Temps[full_raw$Month == i]
  short_table[1, i] = min(temp)
  short_table[2, i] = quantile(temp, 0.25)
  short_table[3, i] = mean(temp)
  short_table[4, i] = quantile(temp, 0.75)
  short_table[5, i] = max(temp)
}

colnames(short_table) = months

short_table = round(short_table, 2)
short_table$Summary = c("Min", "1st_Q", "Mean", "3rd_Q", "Max") 
short_table = short_table %>% select(Summary, everything()) %>% flextable()

short_table
save_as_image(short_table, path = "Short_table.png")
```

# Boxplots

```{r}
ggplot(full_raw, aes(x = as.factor(Month) ,  y = Temps, fill = as.factor(Month))) + 
  geom_boxplot() + 
  theme(legend.position = "none") + 
  labs(x = "Month", y = "Temperature in Celsius", title = "Sacramento Temperature Boxplots")

```

